version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis-server
    environment:
      - APP_ENV_NAME=local

  db:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=example
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis-server:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
  pgdata:
