bind = "0.0.0.0:5000"
env_name = "PROD"
REDIS_URL = "redis://MyRedisDatae:5wJs8yv9cEuWEvGSVpolUVDZASLv99zY@redis-17916.c1.ap-southeast-1-1.ec2.cloud.redislabs.com:17916"
DATABASE_URL = "postgres://oucbjkul:uTYVlGzY_oyzQ1MiiyCqZu1urBji3TTl@arjuna.db.elephantsql.com:5432/oucbjkul"
